# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: jdx/mise-action@v2
      with:
        version: latest # [default: latest] mise version to install
        install: true # [default: true] run `mise install`
        cache: true # [default: true] cache mise using GitHub's cache

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
